version: '3'

services:
  client:
    build: ./client
    restart: always
    ports:
      - "80:3000"
    environment:
      SERVER_ENDPOINT: ${SERVER_ENDPOINT}
      ENABLE_APPLICATIONS: ${ENABLE_APPLICATIONS}
    depends_on:
      - yoga-server
  yoga-server:
    build: ./server
    restart: always
    ports:
      - "4000:4000"
    environment:
      PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
      SERVER_ENDPOINT: ${SERVER_ENDPOINT}
      FRONTEND_URL: ${FRONTEND_URL}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
      PRISMA_SECRET: ${PRISMA_SECRET}
      APP_SECRET: ${APP_SECRET}
      GOOGLE_OAUTH_CLIENTID: ${GOOGLE_OAUTH_CLIENTID}
      GOOGLE_OAUTH_CLIENTSECRET: ${GOOGLE_OAUTH_CLIENTSECRET}
      ENABLE_APPLICATIONS: ${ENABLE_APPLICATIONS}
      PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET}
    volumes:
      - files:/app/files
    depends_on:
      - prisma
    # also db, but since prisma depends on it db isn't added here

  prisma:
    image: prismagraphql/prisma:1.29
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_SECRET: ${PRISMA_SECRET}
      PRISMA_CONFIG: |
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: prisma
            migrations: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: prisma
    volumes:
      - mysql:/var/lib/mysql
volumes:
  files:
  mysql:

